FROM alpine:3.18.5@sha256:34871e7290500828b39e22294660bee86d966bc0017544e848dd9a255cdf59e0

WORKDIR /app
COPY . .
RUN apk update && \
    apk add go && \
    go mod download && \
    go mod verify && \
    GO111MODULE=on go get github.com/githubnemo/CompileDaemon && \
    go install github.com/githubnemo/CompileDaemon && \
    go build -o /usr/local/bin/youshallnotpass .

ENTRYPOINT /root/go/bin/CompileDaemon --build="go build -o /usr/local/bin/youshallnotpass"
