FROM alpine:3.19.0@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48

WORKDIR /app
COPY . .
RUN apk update && \
    apk add go && \
    go mod download && \
    go mod verify && \
    GO111MODULE=on go get github.com/githubnemo/CompileDaemon && \
    go install github.com/githubnemo/CompileDaemon && \
    go build -o /usr/local/bin/youshallnotpass .

ENTRYPOINT /root/go/bin/CompileDaemon --build="go build -o /usr/local/bin/youshallnotpass"
