FROM golang:1.21@sha256:24a09375a6216764a3eda6a25490a88ac178b5fcb9511d59d0da5ebf9e496474 AS builder

ARG GOPROXY

WORKDIR /app
COPY . .
RUN go mod download && \
    go mod verify && \
    CGO_ENABLED=0 go build -o main \
    .

FROM gitlab/gitlab-runner:alpine-bleeding

ARG CI_COMMIT_REF_NAME="development"

ENV RUNNER_BUILDS_DIR="/tmp/builds" \
    RUNNER_CACHE_DIR="/tmp/cache" \
    CUSTOM_CONFIG_EXEC="/var/gitlab_custom_executor/config.sh" \
    CUSTOM_PREPARE_EXEC="/var/gitlab_custom_executor/prepare.sh" \
    CUSTOM_RUN_EXEC="/var/gitlab_custom_executor/run.sh" \
    CUSTOM_CLEANUP_EXEC="/var/gitlab_custom_executor/cleanup.sh"

RUN apk add --no-cache docker-cli jq openssl && rm -rf /var/cache/apk/*

COPY --from=builder /app/main /usr/local/bin/youshallnotpass
COPY custom_executors/gitlab_custom_executor /var/custom-executor
