FROM golang:1.20@sha256:5865f52f9f277b951610d2ab0b7a14b24cadef7709db26de3320c018fbd4550c AS builder

ARG GOPROXY

WORKDIR /app
COPY . .
RUN go mod download && \
    go mod verify && \
    CGO_ENABLED=0 go build -o main \
    .

FROM gitlab/gitlab-runner:alpine-bleeding

ARG CI_COMMIT_REF_NAME="development"

ENV RUNNER_BUILDS_DIR="/tmp/builds" \
    RUNNER_CACHE_DIR="/tmp/cache" \
    CUSTOM_CONFIG_EXEC="/var/gitlab_custom_executor/config.sh" \
    CUSTOM_PREPARE_EXEC="/var/gitlab_custom_executor/prepare.sh" \
    CUSTOM_RUN_EXEC="/var/gitlab_custom_executor/run.sh" \
    CUSTOM_CLEANUP_EXEC="/var/gitlab_custom_executor/cleanup.sh"

RUN apk add --no-cache docker-cli jq openssl && rm -rf /var/cache/apk/*

COPY --from=builder /app/main /usr/local/bin/youshallnotpass
COPY custom_executors/gitlab_custom_executor /var/custom-executor
